try without cache

diff --git a/.github/actions/nix/setup_nix/action.yml b/.github/actions/nix/setup_nix/action.yml
--- a/.github/actions/nix/setup_nix/action.yml
+++ b/.github/actions/nix/setup_nix/action.yml
@@ -65,27 +65,27 @@ runs:
         echo ${{ inputs.target }} > /tmp/nix_target # Create a file to indicate which target are we using (so we don't need to re-specifify target to run_bash_command_in_nix)
         echo ${{ inputs.nix_path }} > /tmp/nix_path # Create a file to indicate where the nix config is (so we don't need to re-specifify nix_path to run_bash_command_in_nix)
 
-    - name: Download cache (for non-self-hosted)
-      if: ${{ !startsWith(runner.name, 'self-hosted') }}
-      shell: bash
-      run: |
-        set -euxo pipefail
+    # - name: Download cache (for non-self-hosted)
+    #   if: ${{ !startsWith(runner.name, 'self-hosted') }}
+    #   shell: bash
+    #   run: |
+    #     set -euxo pipefail
 
-        echo "Latest nix cache:"
+    #     echo "Latest nix cache:"
 
-        wget -q "https://storage.googleapis.com/splice-nix-cache-public/${cache_key}.tar.gz" -O cache.tar.gz || true
-        # TODO (#2663): restore this, keep in mind that caches from a different HOME dir will not work
-        # if [ ! -s cache.tar.gz ]; then
-          # echo "Cache not found, fetching latest instead"
-          # latest=$(curl https://storage.googleapis.com/storage/v1/b/splice-nix-cache-public/o | jq -r '.items | sort_by(.updated) | .[-1].name')
-          # wget -q "https://storage.googleapis.com/splice-nix-cache-public/${latest}" -O cache.tar.gz
-        # fi
+    #     wget -q "https://storage.googleapis.com/splice-nix-cache-public/${cache_key}.tar.gz" -O cache.tar.gz || true
+    #     # TODO (#2663): restore this, keep in mind that caches from a different HOME dir will not work
+    #     # if [ ! -s cache.tar.gz ]; then
+    #       # echo "Cache not found, fetching latest instead"
+    #       # latest=$(curl https://storage.googleapis.com/storage/v1/b/splice-nix-cache-public/o | jq -r '.items | sort_by(.updated) | .[-1].name')
+    #       # wget -q "https://storage.googleapis.com/splice-nix-cache-public/${latest}" -O cache.tar.gz
+    #     # fi
 
-        sudo mkdir -p /cache/nix/${cache_key}
+    #     sudo mkdir -p /cache/nix/${cache_key}
 
-        if [ -s cache.tar.gz ]; then
-          sudo tar -xzf cache.tar.gz -C /cache/nix/${cache_key}
-        fi
+    #     if [ -s cache.tar.gz ]; then
+    #       sudo tar -xzf cache.tar.gz -C /cache/nix/${cache_key}
+    #     fi
 
     - name: Restore nix
       id: restore_nix
